### ISSUE TITLE
support for fake URLs

### ISSUE THREAD

**Issue by Bhupesh-V** [casvanluijtelaar/faker.dart#1]
Hey! first of thanks for creating this package ❤️ 

It would be nice to have support for generating fake URLs (ref: https://github.com/brianvoe/gofakeit#internet)

Let me know if this can be added into the scope for the project, would love to help/contribute

**Comment by casvanluijtelaar** [comment]
Yes, actually! There is an internet module planned since it was also part of the original faker.js library. I just haven't got around to implementing it yet. Of course if you want to contribute I'd love to see it! unfortunatly the original faker.js package is no longer available but here's a   [gist with the original implementation](https://gist.github.com/casvanluijtelaar/b39ab23f8f12a072382c95f269579e82)

**Comment by Bhupesh-V** [comment]
> Yes, actually! There is an internet module planned since it was also part of the original faker.js library. I just haven't got around to implementing it yet. Of course if you want to contribute I'd love to see it! unfortunatly the original faker.js package is no longer available but here's a [gist with the original implementation](https://gist.github.com/casvanluijtelaar/b39ab23f8f12a072382c95f269579e82)

cool I will work around this weekend to share a draft PR, thanks for the gist link

**Comment by Bhupesh-V** [comment]
Hey is it ok if we create a `dataset.json` to store TLDs, wdyt?
We can use this list of TLDs by IANA https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by casvanluijtelaar** [comment]
ah yes sorry I forgot to mention that, faker.js used json files for it's localization and datasets. We do something similar. in `lib/src/locales` you can find all the language specific datasets. and they get converted to dataclasses you can find in `lib/src/models`. you can fetch localized data using `Faker.locale` (see other modules for example). if you need to add to the current dataset you need to add it to the data model (`models/internet.dart` ) and at the least add some english datasets
