### ISSUE TITLE
faker.internet.email() sometime generate invalid email with space

### ISSUE THREAD

**Issue by linchen2chris** [casvanluijtelaar/faker.dart#11]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/3970087/196048797-4b8c901d-116b-409b-bb0b-b37c81bee666.png">
we use faker email to generate email, sometime email is invalie

**Comment by casvanluijtelaar** [comment]
seems like some included combinations might have a space in between, should be an easy fix

**Comment by casvanluijtelaar** [comment]
fixed in [0.1.9](https://pub.dev/packages/faker_dart)
