### ISSUE TITLE
Error when use date.between

### ISSUE THREAD

**Issue by mdeandrea-mrmilu** [casvanluijtelaar/faker.dart#12]
When use `date.between` I had this error:
`RangeError: max must be in range 0 < max ≤ 2^32, was 0`

Example:
```dart
final faker = Faker.instance;
faker.date.between(DateTime(2021), DateTime(2021,  12))
```

**Comment by casvanluijtelaar** [comment]
couldn't directly replicate it, but I can see how it could technically happen. I've modified the date.between to make sure it never happens. available in [0.1.11](https://pub.dev/packages/faker_dart)
