### ISSUE TITLE
fullName returns "Instance of 'Name'" for middleName

### ISSUE THREAD

**Issue by rmvermeulen** [casvanluijtelaar/faker.dart#15]
`fullName` returns things like "Esta Instance of 'Name' Hoppe".

I think this is the [offending bit](https://github.com/casvanluijtelaar/faker.dart/blob/5465ef6917d575cfe844a6c3d436106b4dd7ea1a/lib/src/name.dart#L48C6-L48C6), accidentally using the cascade operator serializes `this` instead of the value returned from `middleName()`.

**Comment by casvanluijtelaar** [comment]
good catch, that's clearly a typo. don't know how that slipped through

**Comment by casvanluijtelaar** [comment]
fixed in [0.2.1](https://pub.dev/packages/faker_dart)
