### ISSUE TITLE
Support creating multiple `Faker` instances

### ISSUE THREAD

**Issue by ahmednfwela** [casvanluijtelaar/faker.dart#16]
Currently the only way to access faker is using the singleton accessor `Faker.instance`, which doesn't work well when we want to generate  multiple Fakers, one for each locale, e.g.

```dart
final fakerEn = Faker()..setLocale(FakerLocaleType.en);
final fakerAr = Faker()..setLocale(FakerLocaleType.ar);
```

**Comment by casvanluijtelaar** [comment]
that's a usecase I did not think about before. will add

**Comment by casvanluijtelaar** [comment]
supported in Faker [0.2.2](https://pub.dev/packages/faker_dart) through the `Faker.unique()` method
