### ISSUE TITLE
Add tip to select random value from enum

### ISSUE THREAD

**Issue by mdeandrea-mrmilu** [casvanluijtelaar/faker.dart#6]
Will be nice add this tip to get a random value of enum:

```dart
enum TypeProject {
  custom,
  simple,
  advanced,
  empty
}

final randomEnum = TypeProject.values[faker.datatype.number(max: TypeProject.values.length)]
```

Maybe can be a helper method too, but with a documentation should be enough.

**Comment by casvanluijtelaar** [comment]
Thanks for using the package! this is basically taking a random entry in a list. although a very common pattern, this package is more about mocking data than utility helper classes it's unlikely this will be added.
