### ISSUE TITLE
Zip Code is replacing the symbols incorrectly

### ISSUE THREAD

**Issue by robin-dojo** [casvanluijtelaar/faker.dart#7]
It seems the postcode is replacing the '#' with alphabet characters and no other symbols are replaced.

Example: 
UK locale is configured correctly to be '??# #??' and this returns '??A B??', when it should be 'AB1 2CD'.

**Comment by robin-dojo** [comment]
Changes need to be made to `address.dart` and `helper_utils.dart` - address needs to change symbols for both '?' and '#', helper_utils needs to change '#' in the alpha replacement part to '?'

**Comment by casvanluijtelaar** [comment]
good catch, should be fixed in 0.1.7

**Comment by robin-dojo** [comment]
Works now - thank you!
