### ISSUE TITLE
Add email address option under internet

### ISSUE THREAD

**Issue by robin-dojo** [casvanluijtelaar/faker.dart#9]
One function we have in the c# faker package is the generation of an email address. Would be a nice feature to have here :)

**Comment by casvanluijtelaar** [comment]
I have the dataset available for that, shouldn't take too long to implement.

**Comment by casvanluijtelaar** [comment]
available in [0.1.8](https://pub.dev/packages/faker_dart)

**Comment by robin-dojo** [comment]
Awesome. Will look to use it straight away 😊
